marketing/urls.py
from django.urls import path

from . import views

app_name = "marketing"
urlpatterns = [
    path("", views.index, name="index"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("", include("marketing.urls", namespace="marketing")),
    path("polls/", include("polls.urls", namespace="polls")),
    path('admin/', admin.site.urls),
] + debug_toolbar_urls()

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("recent/", views.RecentView.as_view(), name="recent"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin

class Question(models.Model):
    def __str__(self):
        return self.question_text + self.pub_date.strftime("%Y-%m-%d %H:%M:%S") + str(self.total_votes)
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        # Check if the published date is within the last day
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    @admin.display(
            boolean=True,
            ordering="pub_date",
            description="Published?",
    )
    def is_published(self):
        now = timezone.now()
        return self.pub_date <= now
    
    def update_votes(self):
        self.total_votes = self.choice_set.aggregate(total_votes=models.Sum("votes"))["total_votes"]
        self.save()

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    total_votes = models.IntegerField(default=0)


class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    
    def votes_count(self):
        return self.votes

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

polls/forms.py
from django import forms

class CreateQuestionForm(forms.Form):
    question_text = forms.CharField()
    pub_date = forms.DateField()
    

marketing/views.py
from django.http import HttpResponse
from django.shortcuts import render
# Acts as a controller

def index(request):
    content = {
        "title": "Home",
        "content": "Welcome to the homepage"
    }
    return render(request, "marketing/index.html", content)

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.db.models import F
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone

from .models import Question, Choice
from .forms import CreateQuestionForm
# Acts as a controller

class IndexView (generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    context_object_name = "question"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"
    context_object_name = "question"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class RecentView(generic.ListView):
    template_name = "polls/recent.html"
    context_object_name = "recent_question_list"

    def get_queryset(self):
        """
        Excludes any questions that aren't published within the past 7 days 
        and have no choices.
        """
        yesterday = timezone.now() - timezone.timedelta(days=7)
        # Exclude Questions with no choices
        return Question.objects.filter(pub_date__gte=yesterday).exclude(choice__isnull=True).order_by("-pub_date")[:5]

class CreateView(generic.edit.FormView):
    template_name = "polls/create_form.html"
    form_class = CreateQuestionForm
    success_url = reverse_lazy("polls:index")


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        question.total_votes = F("total_votes") + 1

        # Save the updated votes count
        question.save()
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

marketing/templates/marketing/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'marketing/style.css' %}?{% now 'U' %}">

<body>
    <h1>{{ title }}</h1>
    <p>{{ content }}</p>
    <div>
        <a href="{%  url 'polls:index' %}">Vote on a Poll</a>
        <a href="{%  url 'polls:create' %}">Create a Poll</a>
    </div>
</body>

polls/templates/polls/create_form.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}?{% now 'U' %}">

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/results.css' %}?{% now 'U' %}">

<body>
    <a href="{% url 'polls:index' %}">Home</a>

    <h1>Vote</h1>
    <p>
        <span>Share poll link: </span>
        <a id="poll-link" href="{{ request.scheme }}://{{ request.get_host }}{% url 'polls:detail' question.id %}">
            {{ request.scheme }}://{{ request.get_host }}{% url 'polls:detail' question.id %}
        </a>
        <button onclick="copyPollLink()" style="border: none; background: none; cursor: pointer;">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
                <path d="M10 4a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h7zm-7 1a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h7a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1H3z"/>
                <path d="M5 0a2 2 0 0 0-2 2v1h1V2a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1h-1v1h1a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H5z"/>
            </svg>
        </button>
    </p>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p class="error"><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
    
    <script>
        function copyPollLink() {
            var pollLink = document.getElementById("poll-link").href;
            navigator.clipboard.writeText(pollLink).then(function() {
                alert("Poll link copied to clipboard!");
            }).catch(function(err) {
                console.error("Failed to copy: ", err);
            });
        }
    </script>  

</body>

        

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}?{% now 'U' %}">

<body>
    <a href="{% url 'marketing:index' %}">Home</a>

    <h1>Polls</h1>
    <div class="category-buttons">
        <a href="{% url 'polls:recent' %}" class="selected">Recent</a>
        <a href="#">Popular</a>
        <a>Oldest</a>
    </div>
    {% if latest_question_list %}
        <table>
            <thead>
                <th>Question</th>
                <th>Votes</th>
                <th>Published</th>
            </thead>
        {% for question in latest_question_list %}
            <tbody>
                <tr>
                    <td>
                        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                    </td>
                    <td>
                        <p>Votes {{ question.total_votes }} </p>
                    </td>
                    <td>
                        <p>{{ question.pub_date }}</p>
                    </td>
                </tr>
            </tbody>
        {% endfor %}
        </table>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>

polls/templates/polls/recent.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}?{% now 'U' %}">

<body>
    <a href="{% url 'marketing:index' %}">Home</a>

    <h1>Polls</h1>
    <div class="category-buttons">
        <a href="{% url 'polls:recent' %}" class="selected">Recent</a>
        <a href="#">Popular</a>
        <a>Oldest</a>
    </div>
    {% if recent_question_list %}
        <table>
            <thead>
                <th>Question</th>
                <th>Votes</th>
                <th>Published</th>
            </thead>
        {% for question in recent_question_list %}
            <tbody>
                <tr>
                    <td>
                        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                    </td>
                    <td>
                        <p>Votes {{ question.total_votes }} </p>
                    </td>
                    <td>
                        <p>{{ question.pub_date }}</p>
                    </td>
                </tr>
            </tbody>
        {% endfor %}
        </table>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>

polls/templates/polls/results.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/results.css' %}?{% now 'U' %}">

<body>
    <a href="{% url 'polls:index' %}">Back to polls</a>
    <h1>Results</h1>
    <h2>Question: {{ question.question_text }}</h2>
    
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    
    <a href="{% url 'polls:detail' question.id%}"><button>Vote Again?</button></a>  

</body>